name: Spring_test
on: push
  
jobs:
  Spring_job:
    runs-on: ubuntu-latest
    
    #services:
      #build:
        #image: maven:3.3-jdk-8        
  
    steps:
      - name: Cd
        run: |
          mkdir repo
          cd repo
      
      - name: Copy repo
        uses: actions/checkout@v2
        
      - name: first check
        run: |
          cd ..
          ls -a
          cd service_spring_boot
          ls -a
      
      - name: set image for build
        run: |
          docker build -t Application .
          docker run Application
          
      - name: second check
        run: docker ps
