name: Spring_test
on: push
  
jobs:
  Spring_job:
    runs-on: ubuntu-latest       
  
    steps:      
      - name: Copy repo
        uses: actions/checkout@v2
        
      - name: Create docker network
        run: docker network create -d ipvlan --subnet=10.10.0.0/8 --gateway=10.10.0.1 internal_net
              
      - name: set image for build 
        run: docker build -t spring_boot .
        
      - name: run application container
        run: docker run --name Try -dp 8080:8080 --net=internal_net --ip=10.10.0.3 spring_boot
          
      - name: send requests
        run: curl http://10.10.0.3:8080?id=4
          #curl -X POST -v -F 'id=4' -F 'name=Aleks' http://10.10.0.3:8080
          #echo "start new"
          
