name: Spring_test
env:
  APPLICATION_NAME: apptry
on: push
  
jobs:
  Spring_job:
    runs-on: ubuntu-latest       
  
    steps:            
      - name: Copy repo 
        #копируем репозиторий на раннер
        uses: actions/checkout@v2
        
      - name: Create docker network
        #создаем сеть 10.10.0.0 с маской 24 с драйвером bridge        
        run: docker network create -d bridge --subnet=10.10.0.0/24 internal_net
              
      - name: set image for build
        #создаем образ spring_boot на раннере из текущей директории раннера
        run: docker build -t spring_boot .
        
      - name: run application container
        #запускаем контейнер apptry
        #-d - запускаем в фоновом процессе, чтоб не висело
        #-p 5050:8080 - прокидываем порт, на котором работает приложение (8080) на порт контейнера (5050)
        #--net internal_net - указываем, в какой сети работает контейнер
        #--ip 10.10.0.12 - задаем ip
        run: docker run --name ${{ env.APPLICATION_NAME }} -d -p 5050:8080 --net internal_net --ip 10.10.0.12 spring_boot
                
      - name: curl1
        run: docker run --name curl --net internal_net --ip 10.10.0.15 curlimages/curl:latest -X POST -L -v -F 'id=4' -F 'name=Aleks' http://10.10.0.1:5050
         
      - name: curl2
        run: docker run --rm --name curl --net internal_net --ip 10.10.0.15 curlimages/curl:latest -L -v http://10.10.0.1:5050/?id=4
