name: Spring_test
on: push
  
jobs:
  Spring_job:
    runs-on: ubuntu-latest       
  
    steps:      
      - name: Copy repo 
        uses: actions/checkout@v2
        
      - name: Create docker network
        run: docker network create -d bridge --subnet=10.10.0.0/24 internal_net
              
      - name: set image for build
        run: docker build -t spring_boot .
        
      - name: run application container
        run: docker run --name Try -d -p 5050:8080 --network 10.10.0.12 spring_boot 
                
      - name: check
        run: docker inspect Try
        
      - name: send requests
        run: curl -v http://localhost:5050?id=3 --retry 3
        
      - name: send requests22
        run: curl -X POST -v -F 'id=4' -F 'name=Aleks' http://localhost:5050 --retry 3
      
      
        
        #curl http://10.10.0.3:8080?id=4
          #curl -X POST -v -F 'id=4' -F 'name=Aleks' http://10.10.0.3:8080
          #echo "start new"
          
