name: Spring_test
on: push
  
jobs:
  Spring_job:
    runs-on: ubuntu-latest       
  
    steps:      
      - name: Copy repo
        uses: actions/checkout@v2
              
      - name: set image for build
        run: | 
          docker build -t spring_boot .
          docker run --name Try -dp 8080:8080 spring_boot
          
      - name: second check
        run: |
          docker ps -a
          echo " "
          docker ps
