name: Spring_test
on: push
  
jobs:
  Spring_job:
    runs-on: ubuntu-latest
    
    #services:
      #build:
        #image: maven:3.3-jdk-8        
  
    steps:      
      - name: Copy repo
        uses: actions/checkout@v2
              
      - name: set image for build
        run: |
          ls
          docker build -t application .
          docker run application
          
      - name: second check
        run: docker ps
