name: Spring_test
on: push
  
jobs:
  Spring_job:
    runs-on: ubuntu-latest
    
    #services:
      #build:
        #image: maven:3.3-jdk-8        
  
    steps:
      - name: Copy repo
        uses: actions/checkout@v2
      
      - name: set container for build
        run: |
          echo "one" >> $GITHUB_ENV
          echo $GITHUB_ENV
          ehco "two >> $GITHUB_ENV
          echo $GITHUB_ENV
